version: '3.8'

services:
  # opus-api:
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3012:3012"
  #   volumes:
  #     - .:/opus-backend
  #     - '/opus-backend/node_modules'
  #   depends_on:
  #     - database

  database:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql:rw
    user: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=opus
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password